config/routes.rb
FeedTracker::Application.routes.draw do
  
  resources :api_keys 

  namespace :api do
    resources  :rss_feeds do
      collection do
        post :create_bulk_rss_feeds , :mock_user_response
      end
    end
  end

  namespace :admin do
    resources :news do
      collection do
        get :news_data ,:news_dashboard ,:update_news_type, :toggle_state, :unlock_news, :lock_news , :hide_destroyed_news, :export
        post  :news_dashboard, :upload, :add_company, :add_person
        delete :remove_company, :remove_person
      end
    end
  end
  namespace :mock do
    resources :user_apis do
      collection do
         post  :mock_user_response
      end
    end
  end
  
   namespace :rm do |rm|
    resources :companies do
      member do 
        get  :show_ajax , :filter_target_company 
        delete :remove_target_company 
      end
      collection do 
        get :show_target_companies , :target_companies , :export_prospects ,:list
        post:create_target_companies
      end
    end 
  end

  devise_for :users

  root :to => 'api_keys#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/company.rb
require 'company_lookup_signature'
# Company class has code that relates to 'companies' table.
class Company < ActiveRecord::Base
  #  has_many :prospects, :class_name => "Contact", :foreign_key => "company_id", :conditions => ["contact_type <> ?", Constants::CONTACT_TYPE::CONTACT]
  belongs_to :user
  belongs_to :verified_company
  has_one :domain
  before_save :update_url_domain, :add_or_update_lookup_signature
#  after_save :update_contact_company_name
  before_create :link_to_verified_companies
  # A company has many contacts
  has_many :contacts
  has_one :title
  has_many :target_companies
  has_many :users, :through => :target_companies
  after_destroy :clear_linkedin_count_cache
  validates :name ,:presence => true , :uniqueness => {:case_sensitive => false}
 
  def info
    if verified_company_id
      CompanyTemplate.first :joins => 'inner join verified_companies on company_templates.id = verified_companies.company_template_id',
        :conditions => "verified_companies.id = #{verified_company_id}"
    else
      self
    end
  end

  def name
    if display_name
      display_name
    else
      read_attribute(:name)
    end
  end

  def name=(name)
    write_attribute(:name, name.squish)
  end

  def self.find_unique name
    if name.nil?
      nil
    else
      name = name.squish
      if name.blank?
        nil
      else
        lookup_signature = name.company_lookup_signature
        vc = VerifiedCompany.find_by_lookup_signature lookup_signature
        name = vc.name if vc
        Company.find_or_create_by_name name
      end
    end
  end

  #Check interesting_sizes for empty before calling
  def interesting_by_size? interesting_sizes
    interesting_sizes.each do |size|
      return true if size.match? self
    end
    return false
  end

  #Check interesting_revenues for empty before calling
  def interesting_by_revenue? interesting_revenues
    interesting_revenues.each do |revenue|
      return true if revenue.match? self
    end
    return false
  end

  def interesting_by_size_and_revenue? interesting_sizes, interesting_revenues
    return ((interesting_sizes.empty? or self.interesting_by_size?(interesting_sizes)) and
        (interesting_revenues.empty? or self.interesting_by_revenue?(interesting_revenues))) ? true : false
  end

  def matching_company_ids
    companies = Company.find :all, :select => "id", :conditions => company_lookup_condition
    companies.collect { |company| company.id }
  end

  def company_lookup_condition
    condition = SmartTuple.new(" OR ")
    condition << {:lookup_signature => self.lookup_signature}
    condition << {:domain_id => self.domain_id} unless self.domain_id.nil?
    condition.compile
  end

  def clear_linkedin_count_cache
    CompanyConnectionsCount.destroy_all :company_id => self.id
  end

  def clear_info
    self.update_attributes(
      :url => nil,
      :phone1 => nil,
      :phone2 => nil,
      :fax => nil,
      :street1 => nil,
      :street2 => nil,
      :city => nil,
      :state => nil,
      :zip => nil,
      :country => nil,
      :employees => nil,
      :revenue => nil,
      :industry => nil,
      :sic_code => nil,
      :location => nil,
      :ticker => nil,
      :stock_symbol => nil,
      :stock_exchange => nil,
      :ownership => nil,
      :employee_range => nil,
      :revenue_range => nil,
      :industry2 => nil,
      :industry3 => nil,
      :sub_industry => nil,
      :sub_industry2 => nil,
      :sub_industry3 => nil,
      :jigsaw_flagged => 0,
      :domain_id => nil
    )
  end

  def has_connections? user_id
    connection = Connection.find(:first, :select => "`connections`.id",
      :joins => "INNER join contacts `contacts`  on `contacts`.id = `connections`.contact_id
                                            INNER join titles titles on contacts.id = titles.contact_id
                                            INNER join companies companies on titles.company_id = companies.id",
      :conditions => ["`connections`.user_id=? AND `titles`.company_id in (?)", user_id, self.matching_company_ids])
    connection ? true : false
  end

  def news(user, from_date, args={})
    conditions = SmartTuple.new(" AND ")
    conditions << ["interesting_news.user_id = ? AND ready = 1
                         AND `companies_in_news`.company_id IN (?)
                         AND published_at > ?", user.id, matching_company_ids, from_date]
    conditions << ["news.headline like ?", "%#{args[:search]}%"] if args[:search]

    News.all(
      :select => "news.id, news.headline,news.reason, news.url, news.news_type_id, news.origin_domain, updated_at, published_at",
      :order => "DATE(news.published_at) desc",
      :joins => "INNER JOIN interesting_news on interesting_news.news_id = news.id
                   INNER JOIN `companies_in_news` ON `companies_in_news`.news_id = `news`.id",
      :conditions => conditions.compile
    )
  end

  def formated_url
    furl = self.url
    if !furl.blank? and !furl.match(/^[http\:\/\/]/) and !furl.match(/^[https\:\/\/]/)
      furl = 'http://' + furl
    end
    return furl
  end

  def merge_company_data(data)
    is_merged = false
    website = "#{data.website}"
    unless website.strip.blank?
      if self.url.blank?
        self.url = website
        is_merged = true
      end
    end
    cphone = "#{data.company_phone}"
    unless cphone.strip.blank?
      if self.phone1.blank?
        self.phone1 = cphone
        is_merged = true
      end
    end
    cfax = "#{data.company_fax}"
    unless cfax.strip.blank?
      if self.fax.blank?
        self.fax = cfax
        is_merged = true
      end
    end
    cst1 = "#{data.company_street1}"
    unless cst1.strip.blank?
      if self.street1.blank?
        self.street1 = cst1
        is_merged = true
      end
    end
    cst2 = "#{data.company_street2}"
    unless cst2.strip.blank?
      if self.street2.blank?
        self.street2 = cst2
        is_merged = true
      end
    end
    ccity = "#{data.company_city}"
    unless ccity.strip.blank?
      if self.city.blank?
        self.city = ccity
        is_merged = true
      end
    end
    cstate = "#{data.company_state}"
    unless cstate.strip.blank?
      if self.state.blank?
        self.state = cstate
        is_merged = true
      end
    end
    czip = "#{data.company_zip}"
    unless czip.strip.blank?
      if self.zip.blank?
        self.zip = czip
        is_merged = true
      end
    end
    ccountry = "#{data.company_country}"
    unless ccountry.strip.blank?
      if self.country.blank?
        self.country = ccountry
        is_merged = true
      end
    end
    return is_merged
  end

  def merge_outlook_company_data(data)
    is_merged = false
    cphone = "#{data[:company_main_phone]}"
    unless cphone.strip.blank?
      if self.phone1.blank?
        self.phone1 = cphone
        is_merged = true
      end
    end
    cfax = "#{data[:business_fax]}"
    unless cfax.strip.blank?
      if self.fax.blank?
        self.fax = cfax
        is_merged = true
      end
    end
    cst1 = "#{data[:business_street]}"
    unless cst1.strip.blank?
      if self.street1.blank?
        self.street1 = cst1
        is_merged = true
      end
    end
    cst2 = "#{data[:business_street_2]}"
    unless cst2.strip.blank?
      if self.street2.blank?
        self.street2 = cst2
        is_merged = true
      end
    end
    ccity = "#{data[:business_city]}"
    unless ccity.strip.blank?
      if self.city.blank?
        self.city = ccity
        is_merged = true
      end
    end
    cstate = "#{data[:business_state]}"
    unless cstate.strip.blank?
      if self.state.blank?
        self.state = cstate
        is_merged = true
      end
    end
    czip = "#{data[:business_postal_code]}"
    unless czip.strip.blank?
      if self.zip.blank?
        self.zip = czip
        is_merged = true
      end
    end
    ccountry = "#{data[:business_countryregion]}"
    unless ccountry.strip.blank?
      if self.country.blank?
        self.country = ccountry
        is_merged = true
      end
    end
    return is_merged
  end

  def append_jsw_data(jsw_attr_hash)
    company_info = JSON.parse(self.to_json)["company"]
    unless company_info.nil?
      vkeys = company_info.select { |k, v| v && !v.to_s.strip.empty? }.collect { |k| k[0] }
      jsw_attr_hash.reject! { |k, v| vkeys.include?(k) }
      self.update_attributes(jsw_attr_hash)
    end
  end

  def self.maintenance_csv_header
    ["id (read-only)", "name", "url", "domain id (Read-only)", "merge into id"]
  end

  def maintenance_csv_row
    [
      "#{self.id}",
      "#{self.name}",
      "#{self.url}",
      "#{self.domain_id}",
      ""
    ]
  end

  def self.safe_destruction ids, update_references_to_this_id
    Company.transaction do
      CompaniesInNews.update_all "company_id = #{update_references_to_this_id}", ["company_id in (?)", ids]
      CompanyConnectionsCount.update_all "company_id = #{update_references_to_this_id}", ["company_id in (?)", ids]
      Contact.update_all "company_id = #{update_references_to_this_id}", ["company_id in (?)", ids]
      TargetCompany.update_all "company_id = #{update_references_to_this_id}", ["company_id in (?)", ids]
      Person.update_all("current_company_id = #{update_references_to_this_id}", ["current_company_id in (?)", ids])
      Person.update_all("last_company_id = #{update_references_to_this_id}", ["last_company_id in (?)", ids])
      Company.destroy_all ["id in (?)", ids]
    end
  end

  private
  def update_contact_company_name
    Contact.update_all("company_name = '#{self.name}'", "company_id = #{self.id}")
  rescue
    # this will handle the company names with (')
    cts = Contact.find(:all, :conditions => ["company_id = #{self.id}"])
    cts.each do |d|
      d.update_attribute(:company_name, self.name)
    end
  end

  def add_or_update_lookup_signature
    self.lookup_signature = self.name.company_lookup_signature
  end

  def update_url_domain

app/controllers/rm/companies_controller.rb
require 'csv'
require 'jigsaw'
require 'prospect_helpers'
require 'company_lookup_signature'

class Rm::CompaniesController < ApplicationController
  include ProspectHelpers::ProspectsByCompany
  include ApplicationHelper
  include Salesforce

  before_filter :init_days_ago_filter, :only => :show_ajax

  def list
  
    name = params[:term]
    unless name.nil? or name.blank? or code_injection? name
      @companies = VerifiedCompany.find(:all, :select => "name", :conditions => ['name LIKE ?', "#{name}%"], :limit => 10, :order => "name")
    else
      @companies = []
    end
    @companies = @companies.map(&:name)
    respond_to do |format|
      format.json { render :json => @companies.to_json }
    end
  end

  def show_ajax
    @company = Company.find(params[:id])
    session[:redirect_path] = "#{get_target_companies_main_path}?days_ago=#{@number_of_days}"
    @sf_link_function = generate_sf_link(current_user)

    if @company
      render :update do |page|
       @connections_limit = 2
        news = @company.news(current_user, @number_of_days.days.ago)

        page.hide 'loading-news-tc'
        if news.present? || URI(request.referer).path == "/main/get_target_companies"

          page.insert_html :bottom, 'companies', :partial => 'company', :locals => {:company => @company, :news => news, :sf_link_function => @sf_link_function}
          page << "$('##{companies_news_container_dom_id(@company)}').fadeIn('slow');"
          page.insert_html :bottom, 'target_companies_list', :partial => 'target_company'
          page << "$(window).scroll()"
        end
      end
    else
      raise "Company #{params[:id]} not found"
    end
  end

  def create_target_companies
    success = false
    name = params[:company][:name]

    if name.blank? or code_injection? name
      @message = "Please enter a name."
    else
      tcs = current_user.target_companies
      if tcs.count < current_user.tc_limit
        @company = Company.find_unique name
        target_company = tcs.find_by_company_id @company.id
        if target_company.nil?
          tcs.create(:company_id => @company.id)
          @message = "Added \"#{@company.name}\" to targets."
          success = true
        else
          @message = "\"#{@company.name}\" is already targeted."
        end
      else
        @need_upgrade = true
      end
    end

    render :update do |page|
      page << "$('#upgrade-membership').modal('show');" if @need_upgrade

      if params[:gritter_enabled].present?
        page << "var unique_id =  $.gritter.add({ title: 'Saved Changes',
                  text: '#{@message}',
                  sticky: false,
                  time: '1000'
                  });
               if(unique_id-1 > 0){
                                   $.gritter.remove((unique_id-1), {
                                                fade: true, // optional
                                                speed: 'fast' // optional
                                    });
                          }"
      else
        page.replace 'message_small_green', :partial => '/layouts/message_small_green'
      end
      
      page[:company_name].value = ""
      page[:company_name].select
      
      if success
        page << "addTargetCompany(#{{:id => @company.id, :name => @company.name}.to_json})" if URI(request.referer).path == "/main/get_target_companies"
        page.insert_html :bottom, 'target_companies_list', :partial => 'target_company' if URI(request.referer).path != "/main/get_target_companies"
      end
    end
  end

  def show
    params[:sf] = 'name' unless params[:sf]

    @company = Company.find(params[:id])
    @connections = current_user.connections.paginate(:all,
                                                     :select => connection_fields,
                                                     :joins => connection_joins,
                                                     :conditions => conditions(@company, params[:search], "Search prospect & 1st Hop"),
                                                     :group => "titles.contact_id",
                                                     :order => "hop_id, contact_first_name, contact_last_name",
                                                     :page => params[:page],
                                                     :per_page => 5)

    li_text_url = current_user.get_linkedin_connection_count_with_url @company
    @li_conn_text = li_text_url[:display_text]
    @li_conn_url = li_text_url[:url]
    @li_conn_count = li_text_url[:count]

    respond_to do |format|
      format.html { render }
    end
  end

  def destroy
    target_company = current_user.target_companies.find_by_company_id params[:id]

    respond_to do |format|
      if (target_company.destroy)
        format.json { render :json => true }
      else
        format.json { render :status => :unprocessable_entity, :json => params[:id] }
      end
    end
  end

  def target_companies
    companies = current_user.companies.all :select => "companies.id, companies.name, companies.display_name", :limit => current_user.tc_limit
    respond_to do |format|
      format.json { render :json => companies.collect { |c| {:id => c.id, :name => c.name} }.to_json }
    end
  rescue Exception => e
    respond_to do |format|
      format.json { render :json => e.message, :status => :internal_server_error }
    end
  end

  #AJAX

  def export_prospects
    render :update do |page|
      company = Company.find(params[:company_id], :select => 'name, display_name')
      DataExportJob.create 'user_id' => current_user.id, 'company_id' => params[:company_id], 'type' => Constants::DATA_EXPORT_TYPE::RM_PROSPECTS
      page.replace_html 'message_small_green', :text => "We have emailed you an excel (csv) file showing prospects in #{company.name}."
    end
  end

  private
  def csv_file?(file_to_upload)
    get_file_format(file_to_upload) == 'csv'
  end

  def save_company(data)
    name = data[:company]
    if TargetCompany.create_target_company(current_user, name)
      @companies << name
      @count += 1
    end
  end

end

app/views/rm/companies/_add_target_company.html.erb
<% width =  local_assigns[:width].nil?? '150px':'185px'  %>

<h5><%= 'Add Target Company' unless local_assigns[:my_placeholder] %></h5>
<%placeholder = local_assigns[:my_placeholder]? "Start typing Target Company" : 'Add Target Company'  %>
<div class="input-append">
  <% form_remote_tag :url => {:controller => "/rm/companies", :action => :create_target_companies} do %>
    <table>
      <tr>
        <td>
          <%= text_field :company, :name, {:id => 'company_name', :placeholder => placeholder , :size => nil, :style => "width: #{width};"} %>
          <button class="btn" type="submit">+</button>
        </td>
      </tr>
    </table>
    <%= hidden_field_tag :gritter_enabled, local_assigns[:gritter_enabled]  %>
    <div id="message_small_green"></div>
  <% end %>
</div>

<%= render :partial => 'layouts/upgrade_membership' , :locals => {:user => user}%>

app/views/rm/companies/_company.html.erb
<div id="<%= companies_news_container_dom_id(company) %>" data-name='<%= company.name.downcase %>'>
  <% display_pic = current_user.display_pic %>
  <% pic_url = display_pic.present? ? display_pic : '/images/new_images/no_pic.gif' %>
  <%= render :partial => 'news/company_news_info',
             :locals => {:info => {:company => company, :news => news}, :pic_url => pic_url, :reminder_btn => true,
                         :sf_link_function => sf_link_function} %>
</div>

app/views/rm/companies/_target_company.html.erb
<% name = @company.name %>
<li id='target-company-<%= @company.id %>' data-name='<%= name.downcase %>'>
  <%= link_to_function(name, "filterTargetCompany(#{@company.id})", :title => 'Filter') %>
  <%= link_to_function('<i class="icon-remove"></i>', "removeTargetCompany(#{@company.id}, '#{name}')", :title => 'Remove') %>
</li>

app/views/rm/companies/list.js.erb
<%= auto_complete_result @companies, :name %>

app/views/rm/companies/show.erb
<style type="text/css">
  .rm-company-conn td {
    border-bottom: none !important;
    padding-bottom: 20px;
  }
</style>
<% display_pic = current_user.display_pic %>
<% pic_url = display_pic.present? ? display_pic : '/images/new_images/no_pic.gif' %>
<div class="content">
  <div>
    <div class="span12 white-background border_bottom">
      <h2><%= @company.name %></h2>

      <div style="padding-left: 20px">
        <%= @company.street1 %>
        <% unless @company.street2.blank? %>,<%= @company.street2 %>
        <% end %>
        <% unless @company.city.blank? %>,<%= @company.city %>
        <% end %>
        <% unless @company.city.blank? %>,<%= @company.state %>
        <% end %>
        <% @company.zip %>
        <% unless @company.country.blank? %>, <%= @company.country %>
        <% end %>
        <br/>
        <% unless @company.location.blank? %>
          Location: <%= @company.location %>
          <br/>
        <% end %>
        <% if  !@company.phone1.blank? %>Phone:   <%= @company.phone1 %>
          <br/>
        <% end %>
        <% if  !@company.url.blank? %>Website:
          <a href="<%= @company.formated_url %>" target="_blank"><%= @company.url %></a><br/>
        <% end %>
        <% if !@company.industry.blank? %>Industry: <%= @company.industry %>
          <br/>
        <% end %>
        <% if !@company.employees.blank? || !@company.employee_range.blank? %>
          Employees: <%= @company.employees.blank? ? @company.employee_range : @company.employees %>
          <br/>
        <% end %>
        <% if !@company.revenue.blank? %>
          Revenue: <%= revenue_format(@company.revenue.to_i) %>
        <% end %>
      </div>
      <div style="padding-left: 20px;padding-top: 10px">
        <%= link_to @li_conn_text, @li_conn_url, :target => "_blank" if @li_conn_count.to_i > 0 %>
      </div>
      <div>
        <table style="width: 100%">
          <tr>
            <td style="padding-left: 20px;">
              <%= render :partial => 'layouts/search_box', :locals => {:placeholder => 'Search prospect & 1st hops'} %>
            </td>
            <td style="text-align: right;width: 50%;padding-right: 20px">
              <%= link_to_remote "<button class='btn btn-primary btn-small'><i class='icon-white icon-briefcase'></i>&nbsp;Export to Excel</button>", :url => export_prospects_rm_companies_path(:company_id => @company.id) %>
              <div id="message_small_green" style="font-size: 12px; color:green;"></div>
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>

  <div>
    <div class="span12 white-background rm-company-conn">
      <table style='margin-left: 20px;width:100%'>
        <tbody class='news-alert'>
          <tr>
            <td class='info' style="border-bottom: 1px solid lightgray;">
              <%= render :partial => 'news/connection', :collection => @connections,
                :locals => {:pic_url => pic_url, :partially_titled => true} %>
            </td>
          </tr>
        </tbody>
      </table>
      <%= will_paginate @connections %>
    </div>
  </div>
</div>