config/routes.rb
FeedTracker::Application.routes.draw do
  
  resources :api_keys 

  namespace :api do
    resources  :rss_feeds do
      collection do
        post :create_bulk_rss_feeds , :mock_user_response
      end
    end
  end

  namespace :admin do
    resources :news do
      collection do
        get :news_data ,:news_dashboard ,:update_news_type, :toggle_state, :unlock_news, :lock_news , :hide_destroyed_news, :export
        post  :news_dashboard, :upload, :add_company, :add_person
        delete :remove_company, :remove_person
      end
    end
  end
  namespace :mock do
    resources :user_apis do
      collection do
         post  :mock_user_response
      end
    end
  end
  
   namespace :rm do |rm|
    resources :companies do
      member do 
        get  :show_ajax , :filter_target_company 
        delete :remove_target_company 
      end
      collection do 
        get :show_target_companies , :target_companies , :export_prospects ,:list
        post:create_target_companies
      end
    end 
  end

  devise_for :users

  root :to => 'api_keys#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/news_type.rb
class NewsType < ActiveRecord::Base
  validates :name ,:presence => true ,:uniqueness => true
attr_accessible :name
  def news(user, from_date, args={})
    condition = SmartTuple.new(" AND ")
    condition << ["interesting_news.user_id = ? AND ready = 1
                         AND published_at > ?", user.id, from_date]
    condition << ["news.headline like ?", "%#{args[:search]}%"] if args[:search]

    News.all(
        :select => "news.id, news.headline,news.reason, news.url, news.news_type_id, news.origin_domain, updated_at, published_at",
        :order => "DATE(news.published_at) desc",
        :joins => "INNER JOIN interesting_news on interesting_news.news_id = news.id
                   INNER JOIN `companies_in_news` ON `companies_in_news`.news_id = `news`.id",
        :conditions => condition.compile
    )
  end

  def self.news_type_data(date)
    NewsType.find_by_sql(
      "SELECT nt.name name, COUNT(DISTINCT n.id) news_count, COUNT(DISTINCT cin.company_id) companies_count, COUNT(DISTINCT ints.user_id) interested_users_count
        FROM news_types nt
          LEFT OUTER JOIN news n ON n.news_type_id = nt.id
          LEFT OUTER JOIN companies_in_news cin ON n.id = cin.news_id
          LEFT OUTER JOIN interesting_news_types ints ON ints.news_type_id = nt.id
          LEFT OUTER JOIN users u ON u.id = ints.user_id
        WHERE DATE(n.published_at)='#{date}' and u.unsubscribed_at IS NULL and u.news_email_frequency=1
        GROUP BY nt.id"
    )
  end
end

app/controllers/admin/news_controller.rb
class Admin::NewsController < ApplicationController
  #before_filter :protect_admin_access
  load_and_authorize_resource
  layout "admin"
  require "ruby-debug"
  def news_sort_order
    "id desc"
  end

  def index
    search = params[:search]
    @news_type_options = [['- Select News Type -', nil]]
    conditions = SmartTuple.new(" AND ")
    conditions << ((search.nil? or search.strip.blank?) ? ["news.updated_at > ?", 1.month.ago] :
        ["news.updated_at > ? and headline like ?", 1.month.ago, "%#{search}%"])

    @news = News.paginate  :conditions => conditions.compile, :include => [:companies],
      :order => news_sort_order, :page => params[:page], :per_page => 100

    @initial_news_ids = @news.collect { |news| news.id }
    NewsType.all.collect { |n| @news_type_options << [n.name, n.id] }
    session[:last_updated_at] = @news.max_by(&:updated_at).updated_at if @news.present?
    session[:last_locked_at] = Time.now

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @news }
    end
  end

  # GET /news/1
  # GET /news/1.xml
  def show
    @news = News.find(params[:id])
    @people = @news.people
    @companies = @news.companies
    @tags = @news.news_indices
    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @news }
    end
  end

  # GET /news/new
  # GET /news/new.xml
  def new
    @news = News.new
    @news.published_at = Time.now
    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find params[:id]
    @people = @news.people
    @companies = @news.companies
    @tags = @news.news_indices
  end

  # POST /news
  # POST /news.xml
  def create
    News.transaction do 
      news = News.new(params[:news].merge(:user_id => current_user.id ))
      params["ready"] == "on" ? news.ready = true : news.blocked = true
      if news.save!
        news_id = news.id
        flash[:notice] = 'News was successfully created.'
        CompaniesInNews.create_company_tag(news.id, params[:companies]) if !params[:companies].blank? && params[:companies].split(' ').count < 5
        IndustriesInNews.create_industry_tag news.id, params[:industries] unless params[:industries].blank?
        Location.tag_in_news(news_id, params[:locations]) unless params[:locations].blank?
        JobTitle.tag_in_news(news_id, params[:job_titles]) unless params[:job_titles].blank?
        redirect_to admin_news_path(news)
      else
        redirect_to new_admin_news_path
      end 
    end
  end

  # PUT /news/1
  # PUT /news/1.xml
  def update
    @news = News.find(params[:id])
    render :update do |page|
      @news.clear_tags
      if @news.update_attributes(params[:news])
        flash[:notice] = 'News was successfully updated.'
        if @news.ready
          @news.on_news_update
          page << "hideBlockLockRow(#{@news.id});"
        end

        if params["commit"] == "Save and Next"
          next_news_edit_path = path_to_edit_next_news(@news.id)
          redirect_to(next_news_edit_path ? next_news_edit_path : admin_news_index_url)
        end
      else
        news_type_options = [['- Select News Type -', nil]]
        NewsType.all.collect { |n| news_type_options << [n.name, n.id] }
        message = "We are unable to save the record. Please try again with valid inputs."
        page.replace 'error', :partial => '/layouts/message_small_red', :locals => {:message => message, :id => 'error'}
        page.replace "news-#{@news.id}", :partial => 'news', :collection => [@news], :as => :news, :locals => {:max => 1, :news_type_options => news_type_options}
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.xml
  def destroy
    @news = News.find(params[:id])
    @news.destroy
    render :json => {:news => @news.id }
  end

  def add_company
    @name = params[:company][:name]
    @news_id = params[:news_id]
    @name = @name.strip unless @name.nil?
    @news = News.find(@news_id)
    
  end

  def remove_company
    @news_id = params[:news_id]
    @company_id = params[:company_id]
  end

  def add_person
    @news = News.find params[:news_id]
    @first_name = params["first_name_#{@news.id}"]
    @last_name = params["last_name_#{@news.id}"]
    @company_name = params["company_#{@news.id}"]
  
  end

  def remove_person
    
  end

  def toggle_state
    news = News.find params[:id]
    if news.ready && params[:state] == 'block' || news.blocked && params[:state] == 'ready' || !news.blocked && !news.ready
      news.blocked = (params[:state] == 'block')
      news.ready = !news.blocked
      news.save
      render :json => {:valid => true , :news => news.id}
     
    else
      render :json => {:valid => false}
    end
  end
  def path_to_edit_next_news last_news_id
    news = News.find :last, :conditions => ["ready = 0 and blocked = 0 and id < ?", last_news_id]
    return news ? edit_admin_news_path(news) : nil
  end

  def update_news_type
    news = News.find(params[:news_id])

    news.update_attribute(:news_type_id, params[:news_type_id])
    render :nothing => true
  end

  def lock_news
    #    running_jobs = RunningJob.find(:all, :conditions => ['created_at >= ?', session[:last_locked_at]])
    running_jobs = []
    news_ids = running_jobs.collect { |job| job.resource_id }
    session[:last_locked_at] = running_jobs.empty? ? session[:last_locked_at] : running_jobs.sort_by(&:created_at).last.created_at

    render :update do |page|
      page << "lockedNewsIds = eliminateDuplicates($.merge(lockedNewsIds, #{news_ids.to_json}));"
      page << "$.each(#{news_ids.to_json}.diff(lockedNewsIds), function(_, news_id) {" +
        "if($('#news-'+news_id).find('td.cleanByBlock').length == 0) {" +
        "hideEditNewsPanel($('#' + news_id), news_id);" +
        "blockRow(news_id);" +
        "}" +
        "});"
    end
  end
  def unlock_news
    locked_news_ids = JSON.parse(params[:locked_news_ids])
    unlocked_news_ids = []
    error_msg = ''

    begin
      all_news = News.find(:all, :conditions => ['updated_at >= ?', session[:last_updated_at]])
      session[:last_updated_at] = all_news.empty? ? (session[:last_updated_at] - 5.seconds) : all_news.sort_by(&:updated_at).last.updated_at
    rescue Exception => e
      error_msg = "alert('Sorry! we are experiencing some problem on server, kindly reload the page. Contact Developers, if problem persists.')"
    end

    news_ids = all_news.collect { |news| news.id }
    all_locked_news_ids = locked_news_ids.zip(news_ids).flatten.compact.uniq

    render :update do |page|
      page << error_msg
      all_locked_news_ids.each do |news_id|
        if RunningJob.find_by_resource_id_and_resource_type(news_id, 1).nil?
          news_type_options = [['- Select News Type -', nil]]
          NewsType.all.collect { |n| news_type_options << [n.name, n.id] }
          page.replace "news-#{news_id}", :partial => 'news', :collection => [News.find(news_id)], :as => :news, :locals => {:max => 1, :news_type_options => news_type_options}
          unlocked_news_ids << news_id
        end
      end
      page << "lockedNewsIds = lockedNewsIds.diff(#{unlocked_news_ids.to_json});"
    end
  end

  def hide_destroyed_news
    init_ids = JSON.parse(params[:initial_news_ids])
    curr_news = News.find_all_by_id(init_ids)
    if curr_news != init_ids.count
      curr_news_ids = curr_news.collect { |news| news.id }
      del_news = init_ids - curr_news_ids
    end

    render :update do |page|
      del_news.each do |news_id|
        page.visual_effect :fade, "tbody#news-#{news_id}"
        page << "initialNewsIds.remove(#{news_id});"
      end
    end
  end

  # Export the Linksv News in to CSV file, since last week
  def export
    ns = NewsSource.find_by_name 'Linksv', :select => :id
    @news = News.find(:all, :conditions => ["updated_at >= ? and news_source_id != ? and ready = 1", 1.week.ago, ns.id])
    file_name = "linksv_news_#{1.week.ago.strftime('%b-%d-%Y')}_to_#{Time.now.strftime('%b-%d-%Y')}.csv"
    csv = %w(Source Headline).to_csv
    @news.each { |news| csv << [news.news_source.name, news.news_headline].to_csv }
    send_data csv, :filename => file_name, :type => "text/csv"
  end

  def news_dashboard
    from = params[:from]
    to = params[:to]
    flash[:notice] = false
    if to.blank? or from.blank?
      flash[:notice] = "Please select duration"
    else
      @days = (from.to_date..to.to_date).map { |date| date.strftime("%Y-%m-%d") }
    end
    respond_to do |format|
      format.html
    end
  end

  def news_data 
    date = params[:day]
    all_sources_count = []
    news_sources = NewsSource.all
    news_sources.each do |news_source|
      source_name = news_source.name
      news_count_by_creation_date = news_source.news.count(:conditions => ["DATE(news.created_at) = ?", date])
      news_count_by_publish_date = news_source.news.count(:conditions => ["DATE(news.created_at) = ? and DATE(news.published_at) = ?", date, date])
      all_news = {:news_count_by_creation_date => news_count_by_creation_date,
        :news_count_by_publish_date => news_count_by_publish_date, :source_name => source_name}
      all_sources_count << all_news
    end

    joins = "INNER JOIN  interesting_news on interesting_news.news_id = news.id"
    group_by = "interesting_news.news_id"

    int_news_by_creation_date = News.find(:all, :select => "news.id",
      :conditions => ["DATE(news.created_at) = ?", date],
      :joins => joins,
      :group => group_by)

    int_news_by_publish_date = News.find(:all, :select => "news.id",
      :conditions => ["DATE(news.created_at) = ? and DATE(news.published_at) = ?", date, date],
      :joins => joins,
      :group => group_by)

    email_alert_count = User.count(:conditions => ["DATE(news_emailed_at) = ?", (date.to_date + 1)])

    news_type_data = NewsType.news_type_data(date)

    render :update do |page|
      page.show('.data-area')

app/helpers/admin/news_helper.rb
module Admin::NewsHelper
  def bg_style(news)
    if news.blocked
      'background-color: lightgray;'
    elsif news.ready
      'background-color: #87D48D;'
    else
      'background-color: #FFFDA2;'
    end
  end

  def processing?(news_id)
#    !!RunningJob.find_by_resource_id_and_resource_type(news_id, 1)
  end
end

app/views/admin/news/_company.html.erb
<li id ="<%="company_#{company.id}_#{news_id}"-%>">
  <%=company.name%> |
  <%=link_to 'remove',remove_company_admin_news_index_path(:company_id=>company.id,:news_id=>news_id),{:style=>"color:red;",:method=>:delete, :remote => true}%> |
  <%= link_to("Search on Jigsaw", "javascript:openPopup('http://www.jigsaw.com/FreeTextSearchCompany.xhtml?opCode=search&freeText="+(company.url || company.name).gsub(' ', '+')+"', '#{company.id}');") -%>
</li>

app/views/admin/news/_edit_news.html.erb
<%= @errors.each { |error| error.message } unless @errors.nil? %>
<%= semantic_form_for news, :url => url, :method => method  , :before => "hideEditNewsPanel($(this), #{news.id})" , :remote => true do |f| %>
    <div style="padding-left:20px;overflow: inherit" class="update-tagging">
      <%= f.inputs do %>
          <% if news.id %>
              <%= f.input :industries, :as => :select, :placeholder => 'Select Industries', :required => false,
                          :input_html => {:id => "ind_#{news.id}", :class => "chzn-select",
                                          :style => "width:300%;margin:2px", :size => 8} %>
              <%= f.input :locations, :as => :select, :placeholder => 'Select Locations', :required => false,
                          :input_html => {:id => "loc_#{news.id}", :class => "chzn-select",
                                          :style => "width:300%;margin:2px", :size => 8} %>
              <%= f.input :job_titles, :as => :select, :placeholder => 'Select Job Titles', :required => false,
                          :input_html => {:id => "jtitle_#{news.id}", :class => "chzn-select",
                                          :style => "width:300%;margin:2px", :size => 8} %>
              <%= f.input :job_functions, :as => :select, :placeholder => 'Select Job Functions', :required => false,
                          :input_html => {:id => "jfn_#{news.id}", :class => "chzn-select",
                                          :style => "width:300%;margin:2px", :size => 8} %>
          <% end %>
      <% end %>
      <div id="more-<%= news.id %>" style="display:none" class="more-details">
        <%= f.input :url, :required => false, :input_html => {:size => 50} %>
        <%= f.input :headline, :required => true, :input_html => {:size => 50} %>
        <%= f.input :published_at, :as => :string, :input_html => {:size => 100, :style => 'width:72%'} %>
      </div>
      <%= f.buttons :style => 'width:100%' do %>
          <%= f.commit_button :label => "Save Changes" %>
      <% end %>
    </div>
<% end %>
<b><%= link_to 'Show More', "javascript:;", :onclick => "toggleExpandedView(#{news.id}, #{company_count})", :id => "expand-view-#{news.id}", :class => "expand-view" %></b>
<%= render :partial => "news_enrichment" %>
<%= render :partial => 'layouts/chosen_javascript' %>

app/views/admin/news/_form.html.erb
<h2>News</h2>
<%= @errors.each{|error| error.message} unless @errors.nil? %>
<%= semantic_form_for @news,:url=>url,:method=>method do |f| %>
  <div style ="padding-left:20px;width:900px;overflow: inherit">
    <%=f.inputs do %>
      <%=f.input :url, :required=>false, :input_html => { :size => 50 }%>
      <%=f.input :headline, :input_html => { :size => 50 }%>
      <%= f.input :description , :input_html => {  :rows => 10, :cols => 20}%>
    <%#=f.input :news_source %>
      <%=f.input :published_at, :as=>:string, :input_html => { :size => 50 }%>      
      <%=f.input :news_type, :as=>:select %>
      <%if @news.id%>
        <%= render :partial=>'news_link', :locals=>{:news => @news} %>
      <%end%>
      <li class="select optional" id="news_industries_input">
        <label for="news_industries_id">Industries</label>
        <%=select_tag "industries", options_from_collection_for_select(Industry.all, "name", "name"),:prompt => "select"%>
      </li> 
      <li class="select optional" id="news_locations_input">
        <label for="news_locations_id">Locations</label>
        <%=  select_tag "locations", options_from_collection_for_select(Location.all, "name", "name"),:prompt => "select"%><br/>
      </li> 
      <li class="select optional" id="news_job_title_input">
        <label for="news_job_title_id">Job Titles</label>
        <%=  select_tag "job_titles", options_from_collection_for_select(JobTitle.all, "name", "name"),:prompt => "select"%><br/>
      </li> 
      <li class="select optional" id="news_companies_input">
        <label for="news_companies_id">Companies</label>
        <%=select_tag "companies", options_from_collection_for_select(Company.all, "name", "name") ,:prompt => "select"%>
      </li>
      <%#*<li class="select optional" id="news_job_functions_input">%>
        <%#*<label for="news_job_functions_id">Job Functions</label>%>
        <%#=select_tag "job_functions", options_from_collection_for_select(JobFunction.all, "id", "name")%><br/>
      <%#*</li>%> 
       
      <li class="radio optional" id="news_ready_input">
        <fieldset>
                  <ol>
                     <li class="ready_true">
                       <label for="news_ready_true">
                         <input id="news_ready_true" name="ready" type="radio" > Ready</label>
                     </li>
                     <li class="ready_false">
                       <label for="news_ready_false">
                         <input checked="checked" id="news_block_true" name="ready" type="radio" value="false">Blocked</label>
                     </li>
                   </ol>
        </fieldset>
      </li>
      

    <%end%>
    <%= f.buttons do %>
      <%= f.commit_button :label => "Save" %>
      <%= f.commit_button :label => "Save and Next" if @news.id %>
    <% end %>

  </div>
<%end%>
<%= render :partial=>'layouts/chosen_javascript' %>

app/views/admin/news/_news.html.erb
<% @news = news %>
<% @companies = @news.companies %>
<% company_count = @companies.count %>
<% @people = @news.people %>
<% source= @news.user %>

<tbody id="news-<%= news.id %>">
<tr class="first last" style="<%= bg_style(news) -%>">
  <div class="news-block">
    <td>
      <%= DateTime.parse("#{news.published_at}").strftime('%d/%m/%y') -%>
    </td>
    <td>
      <%= @companies.collect { |c|  c.name }.join(', ') -%>
    </td>
    <td>
      <%= source.user_name if source.present? -%>
    </td>
    <td>
      <%= select_tag :news_type_select, options_for_select(news_type_options, :selected => @news.news_type_id),
                     :onchange => "updateNewsType('#{@news.id}', this.value);", :id => "news-type-select-#{@news.id}" -%>
    </td>
    <td>
      <%= render :partial => 'news_link', :locals => { :news => news, :short_headline => true } %>
    </td>
    <td>
      <%= radio_button_tag "state-#{news.id}", 'ready', news.ready, :onclick => "changeNewsState(#{news.id}, 'ready')" %>
      Ready
      <%= radio_button_tag "state-#{news.id}", 'block', news.blocked, :onclick => "changeNewsState(#{news.id}, 'block')" %>
      Block
    </td>
    <td><%= link_to 'Edit', "javascript:;", :onclick => "editNewsPanel(#{news.id}, #{company_count});" %></td>
    <td><%= link_to 'Destroy', "javascript:;", :onclick => "deleteNews(#{news.id});" %></td>
  </div>
</tr>
<tr>
  <td colspan="8">
    <div id="<%= news.id %>" style="width:100%;display:none" class="edit-news-block">
      <%= render :partial => "edit_news", :locals => {:company_count => company_count, :news => @news, :url => admin_news_path(@news), :method => :put} %>
    </div>
    <hr/>
  </td>
</tr>
<% if processing?(news_id = news.id) %>
    <script type="text/javascript">
        news_id = <%= news_id %>;
        lockedNewsIds.push(news_id);
        blockRow(news_id);
    </script>
<% end %>
</tbody>

app/views/admin/news/_news_link.html.erb
<% headline = local_assigns[:short_headline] ? news.headline : news.news_headline %>
<% description_id = "description_#{news.id}" %>
<%= link_to((truncate headline, :length => 65), "javascript:openPopup('#{news.url}', '#{news.id}');", :onMouseover => "toggleDisplay('#{description_id}')", :onMouseout => "toggleDisplay('#{description_id}')") -%>
<div id ="<%= description_id %>" style="z-index: 200;width:500px;padding:5px;position: absolute;border-width: 1px;background-color: white;display: none;border-style: solid;border-color: black">
  <%=(news.description).html_safe if news.description%>
</div>

app/views/admin/news/_news_type_data.html.erb
<hr/>
<table class="table table-bordered news-type-data" style="padding:0">
  <tbody>
  <tr>
    <th>News Type</th>
    <th>No of news</th>
    <th>No of companies</th>
    <th>Interested users for news type</th>
  </tr>

  <% news_type_data.each do |news_type| %>
      <tr>
        <td><%= news_type.name %></td>
        <td><%= news_type.news_count %></td>
        <td><%= news_type.companies_count %></td>
        <td><%= news_type.interested_users_count %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<hr/>

app/views/admin/news/_person.html.erb
<li id="<%= "person_#{person.id}_#{news_id}"-%>">
	<%= person.full_name-%><%= ", #{person.current_designation_title}" unless person.current_designation_title.blank?-%><%= ", #{person.current_company_name}" unless person.current_company_name.blank?-%> | <%= link_to 'remove', { :action => 'remove_person' ,:person_id => person.id,:news_id=>news_id } , { :style=>"color:red;", :method=>:delete , :remote => true } %>
</li>

app/views/admin/news/_tag.html.erb
<li id ="<%="tag_#{tag.id}"-%>">
  <%=tag.tag-%> : <%=tag.value-%> | <%=link_to_remote 'remove',:url=>remove_tag_admin_news_path(:id=>tag.id),:method=>:delete%>
</li>

app/views/admin/news/add_person.js.erb
<%  company = Company.find_or_create_by_name @company_name.strip unless @company_name.blank? or @company_name.nil?
    company_id = company ? company.id : nil
    title_name = params[:title]
    title = Designation.find_or_create_by_name title_name.strip unless title_name.blank? or title_name.nil?
    title_id = title ? title.id : nil
    last_company_name = params[:last_company]
    last_company = Company.find_or_create_by_name last_company_name.strip unless last_company_name.blank? or last_company_name.nil?
    last_company_id = last_company ? last_company.id : nil
    last_title_name = params[:last_title]
    last_title = Designation.find_or_create_by_name last_title_name.strip unless last_title_name.blank? or last_title_name.nil?
    last_title_id = last_title ? last_title.id : nil

    person = Person.find_or_create_by_first_name_and_last_name_and_current_company_id_and_current_designation_id :first_name => @first_name, :last_name => @last_name, :current_company_id => company_id, :last_company_id => last_company_id, :current_designation_id => title_id, :last_designation_id => last_title_id
    pin = PeopleInNews.find_by_news_id_and_person_id @news.id, person.id
    message_id = "message_small_red_people_#{@news.id}"
    if pin
      message = "Person is already in news."
    else
      @news.people_in_news.create :person_id => person.id
    %>
    $("#people-<%=@news.id%>").append("<%= escape_javascript(render(:partial => "person", :locals => {:person => person, :news_id => @news.id})).html_safe %>");
    $("#<%=message_id%>").html("<%= escape_javascript(render(:partial => "/layouts/message_small_red",   :locals => {:message => '', :id => message_id})).html_safe %>"); 
  <%    if @news.ready
        @news.on_news_update
      end
      @message = "Person is already in news."
    end
%>

app/views/admin/news/index.html.erb
<script type="text/javascript">
  lockedNewsIds = [];
  if(navigator.userAgent.toLowerCase().indexOf('firefox') > -1) alert('WARNING! Mozilla Firebox is not compatible for news editing purpose. Please use Chrome or Chromium.');
</script>
<% news = @news %>
<div id="container">
  <div id="content" class="clearfix">
    <div id="mainContent" class="clearfix">
<%#= render :partial => "/layouts/top_tabs_menu"%>
      <div id="RHS_col_admin_general">
        <h1>News</h1>
        <h3><%= "Last news delivery ran at #{@last_email_delivery_at}"-%></h3>
        <%= render :partial => "layouts/search_box", :locals => { :width => 347 } %>
        <div style="text-align: center;" id="error"></div>
        <table style="width:100%">
          <tr>
            <td><h2>Companies in news</h2></td>
            <%#*<td style="text-align: right;padding-right: 27px">%>
            <%#*<a href="/admin/news/new" id="add-news">Add News</a>%>
            <%#*</td>%>
            <td style="text-align: right;padding-right: 27px">
              <a href="/admin/news/new" id="add-news" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-primary" role="button" aria-disabled="false"><span class="ui-button-icon-primary ui-icon ui-icon-plusthick"></span><span class="ui-button-text">Add News</span></a>
            </td>
          </tr>
        </table>
        <table cellspacing="0" border="0" class="data-table box-table shopping-cart" id="shopping-cart-table">
          <thead>
            <tr class="first last">
              <th>Published at</th>
              <th style="width:20em">Companies</th>
              <th>Source</th>
              <th>News Type</th>
              <th>Headline</th>
              <th style="width:94px">State</th>
              <th>Edit</th>
              <th>Destroy</th>
            </tr>
          </thead>
          <tbody>
            <%= render :partial => "news", :collection => @news ,:as => :news, :locals => { :max => @news.length, :news_type_options => @news_type_options }%>
          </tbody>
        </table>
        <div style="width:80%;float:left;"><%= will_paginate news %></div>
        <a href="/admin/news/export" title="Download list of all non linksv news with ready state since last week" style="float: right;margin-right: 25px;">Export Non Linksv News</a>
      </div>
    </div>
  </div>
</div>

app/views/admin/news/new.html.erb
<div id="container">
  <div id="content" class="clearfix">
    <div id="mainContent" class="clearfix">
      <%#= render :partial => "/layouts/top_tabs_menu"%>
      <div id="RHS_col_admin_regular" style="height:1200px">
        <%=  render :partial => "form", :locals=>{:url=>admin_news_index_path(@news),:method=>:post}%>
      </div>
    </div>
  </div>
</div>

app/views/admin/news/remove_company.js.erb
  <%    if @news_id and @company_id
        cin = CompaniesInNews.find_by_news_id_and_company_id @news_id, @company_id
        cin.destroy if cin 
  %>
$("#company_"+<%=@company_id%>+"_"+<%= @news_id%>).remove();
<%
    news_id = @news_id
    news_type_options = [['- Select News Type -', nil]]
    NewsType.all.collect { |n| news_type_options << [n.name, n.id] } 
 %> 
   $("#news-<%=news_id%>").replaceWith("<%= escape_javascript(render(:partial => "news",:collection => [News.find(news_id)], :as => :news, :locals => {:max => 1, :news_type_options => news_type_options})).html_safe %>");
  <%      news = News.find(@news_id)
        if news.ready
          news.on_news_update
       end
      end
%>  